import pandas as pd
import numpy as np
df = pd.read_csv('/home/jarvis/student_data/student-por.csv', sep=';')
print("--- 1. Checking Collinearity (Do they move together?) ---")
print("Pearson correlation between features:")
print(f"Medu vs Fedu:        {df['Medu'].corr(df['Fedu']):.3f}")
print(f"Dalc vs Walc:        {df['Dalc'].corr(df['Walc']):.3f}")
print(f"goout vs freetime:   {df['goout'].corr(df['freetime']):.3f}")
print("\n--- 2. Checking Predictive Power (Does clubbing help?) ---")
print("Pearson correlation with the Final Grade (G3):")
print(f"Medu alone:          {df['Medu'].corr(df['G3']):.3f}")
print(f"Fedu alone:          {df['Fedu'].corr(df['G3']):.3f}")
print(f"Clubbed (Pedu):      {(df['Medu'] + df['Fedu']).corr(df['G3']):.3f}")
print("-")
print(f"Dalc alone:          {df['Dalc'].corr(df['G3']):.3f}")
print(f"Walc alone:          {df['Walc'].corr(df['G3']):.3f}")
print(f"Clubbed (Alc):       {(df['Dalc'] + df['Walc']).corr(df['G3']):.3f}")
print("-")
print(f"goout alone:         {df['goout'].corr(df['G3']):.3f}")
print(f"freetime alone:      {df['freetime'].corr(df['G3']):.3f}")
print(f"Clubbed (Unstruct):  {(df['goout'] + df['freetime']).corr(df['G3']):.3f}")
print("-")
job_mapping = {'at_home': 0, 'other': 1, 'health': 1, 'services': 1, 'teacher': 2}
mjob_mapped = df['Mjob'].map(job_mapping)
fjob_mapped = df['Fjob'].map(job_mapping)
pjob = mjob_mapped + fjob_mapped
print(f"Mjob mapped alone:   {mjob_mapped.corr(df['G3']):.3f}")
print(f"Fjob mapped alone:   {fjob_mapped.corr(df['G3']):.3f}")
print(f"Clubbed (Pjob):      {pjob.corr(df['G3']):.3f}")